### ISSUE TITLE
Maven build failed

### ISSUE THREAD

**Issue by zoharaharoni** [twitter-archive/snowflake#14]
Hi,
I've downloaded snowflake and tried to build it. I'm getting the following error:

[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.2:compile (thrift-sources) on project snowflake: Execution thrift-sources o
f goal com.twitter:maven-finagle-thrift-plugin:0.0.2:compile failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.2:compile (thrift-sources)
on project snowflake: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.2:compile failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.2:compile fa
iled.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:188)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:174)
        at org.codehaus.plexus.util.FileUtils.copyStreamToFile(FileUtils.java:1059)
        at com.twitter.FinagleThriftRunner.getBinary(FinagleThriftRunner.java:43)
        at com.twitter.FinagleThriftRunner.compile(FinagleThriftRunner.java:54)
        at com.twitter.AbstractFinagleThriftMojo.execute(AbstractFinagleThriftMojo.java:165)
        at com.twitter.FinagleThriftCompileMojo.execute(FinagleThriftCompileMojo.java:22)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
C:\Users\zohar\Downloads\snowflake-master>

**Comment by bixu** [comment]
I'm also seeing something like this, but on SmartOS (Illumos kernel, Solaris descendent).

**Comment by ohohoreilly** [comment]
Isn't this the exact same issue as https://github.com/twitter/snowflake/issues/8
